name: 'How do I'
description: 'Looking for an issue and post results to an issue in response.'
inputs:
  search:
    description: 'What is your issue ?'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./howdoi/
      with: 
        search: ${{ inputs.search }}
