name: 'How do I'
description: 'Search code solution with howdoi '
inputs:
  search:
    description: 'What is your issue ?'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.search }}
