name: 'How do I'
description: 'Search code solution with howdoi '
inputs:
  search:
    description: 'What is your issue ?'
    required: true
outputs:
  answer: # id of output
    description: 'Your solution'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.search }}
