on:
  issues:
    types:
      - opened
name: Comment issue
jobs:
  howdoi:
    runs-on: ubuntu-latest
    name: A job to use howdoi
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      